#!/bin/sh
. /lib/functions/uci-defaults.sh

board_config_update
board=$(board_name)

case "$board" in
gemtek,xr1710g-ubi)
	ucidef_set_interfaces_lan_wan "lan2 lan3 lan4" "wan"
	;;
esac

board_config_flush
exit 0
