#!/bin/sh

# === radio0: 2.4GHz 配置 ===
uci set wireless.radio0.disabled='0'
uci set wireless.radio0.country='US'
uci set wireless.radio0.channel='6'
uci set wireless.radio0.htmode='EHT40'     # Wi-Fi 7 (802.11be)
uci set wireless.default_radio0.ssid='freedom1'
uci set wireless.default_radio0.encryption='psk2+ccmp'
uci set wireless.default_radio0.key='12345678'

# === radio1: 5GHz 配置 ===
uci set wireless.radio1.disabled='0'
uci set wireless.radio1.country='US'
uci set wireless.radio1.channel='48'
uci set wireless.radio1.htmode='EHT80'     # Wi-Fi 7 (802.11be)
uci set wireless.default_radio1.ssid='freedom2'
uci set wireless.default_radio1.encryption='sae-mixed'
uci set wireless.default_radio1.key='12345678'

# === radio2: 6GHz 配置 ===
uci set wireless.radio2.disabled='0'
uci set wireless.radio2.country='US'
uci set wireless.radio2.channel='53'
uci set wireless.radio2.htmode='EHT160'    # Wi-Fi 7 (802.11be)
uci set wireless.default_radio2.ssid='freedom3'
uci set wireless.default_radio2.encryption='sae'
uci set wireless.default_radio2.ieee80211w='2'
uci set wireless.default_radio2.key='12345678'

uci commit wireless
wifi reload
exit 0
